development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: davidjackson
  password: rtfm4me
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: davidjackson
  password: rtfm4me
